/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    MobileMenu: typeof import('./components/MobileMenu.vue')['default']
    NavMenu: typeof import('./components/MobileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
